### PR TITLE
update compatablity for homeassistant lutron_caseta component

### PR DESCRIPTION
**Pull request by danaues**
This update adds initial compatibility with the homeassistant lutron_caseta component.

1. Added the processor as devices[1], as this is where the caseta bridge ends up for the caseta line.  This allows the HA integration to complete the setup phase.
2. Adjusted serial numbers and name assignments for zones, control stations, buttons to be consistent with how the caseta devices are imported

I've tested with Caseta Smartbridge Pro, and RA3.  Both systems have dimmers and picos.

### CODE REVIEW

**Comment by danaues** [comment]
This update enables the pairing process to work with RA3.

I've added the lutron-root CA as an asset for pairing with the RA3 Processors.

Currently we try RA3 pairing if the SSL Verification fails assuming it might be RA3 instead of caseta. Not a great way of detecting RA3.  Perhaps there is a better way of detecting caseta vs RA3 before attempting an SSL connection.

Tested on Caseta Smartbridge Pro and RA3 Processor.

Confirmed working with Home Assistant and lutron_caseta component

**Comment by danaues** [comment]
Updates:
1. Query the /project url to determine the type of bridge, and then load either caseta, or ra3 based on response
2. clean up on variable name/use in processor loading

Tested on ra3 and caseta

**Comment by MouseRatt** [comment]
Hi @danaues 

Sorry if this is the wrong place to ask, but do you have instructions for
How to implement this into HA deployment before the changes/pull requests are committed? Have a fairly large ra3 deployment I'd like to test it on. Also have a few other RA3 users interested that could test.

Thanks!

**Comment by danaues** [comment]
@MouseRatt 

I'm running the hassio OS, and this is how I do it:

go to your console on your HA system
you should have the "ha > " prompt
enter the command "login", and you get a "#" prompt
enter the command "docker exec -it $(docker ps -f name=homeassistant -q) bash" and you get a "bash-5.1#" prompt
enter the command "pip uninstall pylutron-caseta" and answer "y" when asked to proceed (or it will skip if not installed)
enter the command "pip install git+https://github.com/danaues/pylutron-caseta@ra3"
restart home assistant using the HA web interface or client
add the "Lutron Caseta" integration using the HA web interface or client

All this will get undone every time you upgrade home assistant, so just repeat these steps after an upgrade to fix it.  You won't have to re-configure or re-add the integration.

good luck!

**Review by johninaustin — APPROVED** [review]

**Comment by SuddenlyEngineer** [comment]
@danaues Getting an issue when I set mine up, following your instructions. I can complete the normal setup flow, up to and including hitting the button on the RA3 bridge to pair it. Unforunately, Home Assistant can't quite get it setup. Not quite sure on what it's getting stuck. I have two keypads and a selection of RA3 dimmers, RA3 switches, RA3 keypads, and forthcoming Sivoia QS shades.

```

Error setting up entry <IP> for lutron_caseta
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self) 
File "/usr/src/homeassistant/homeassistant/components/lutron_caseta/__init__.py", line 128, in async_setup_entry
    await bridge.connect()
File "/usr/local/lib/python3.9/site-packages/pylutron_caseta/smartbridge.py", line 104, in connect
    await self._login_completed
File "/usr/local/lib/python3.9/site-packages/pylutron_caseta/smartbridge.py", line 586, in _login
    await self._load_ra3_devices()
File "/usr/local/lib/python3.9/site-packages/pylutron_caseta/smartbridge.py", line 651, in _load_ra3_devices
    await self._load_ra3_control_stations(area)
File "/usr/local/lib/python3.9/site-packages/pylutron_caseta/smartbridge.py", line 705, in _load_ra3_control_stations
    await self._load_ra3_station_device(combined_name, device_json)
File "/usr/local/lib/python3.9/site-packages/pylutron_caseta/smartbridge.py", line 726, in _load_ra3_station_device
    device_serial = device_json.Body["Device"]["SerialNumber"]
    
KeyError: 'SerialNumber'

**Comment by danaues** [comment]
@SuddenlyEngineer 

Interesting, you must have a control device that isn't providing a SerialNumber key.  All my pico devices have it, curious which device it is.

I've just pushed a change to my repo that checks for the SerialNumber key first.  It will use the serial if it finds it, otherwise it will use the device area, name, and type in place of the serial.

Try repeating the installation instructions to download the updated version and see if it's able to complete.

Let me know how it goes

**Comment by danaues** [comment]
Just looking through the responses that @johninaustin saved within the project.  Sure enough the Keypads and Audio pico's don't provide the SerialNumber key, but the picos I have do.

**Comment by SuddenlyEngineer** [comment]
@danaues Worked, thanks for the quick fix!

**Pull request merged**
